### ISSUE TITLE
'WebDriver' object has no attribute 'find_element_by_tag_name'

### ISSUE THREAD

**Issue by ParityError** [a-maliarov/amazoncaptcha#89] opened 2023-05-14 05:18 UTC
I have two issues, so I'll mention them both here. Using the provided examples I get errors:

**_fromlink:_**
```
requests.exceptions.MissingSchema: Invalid URL '<selenium.webdriver.firefox.webdriver.WebDriver (session="4ff4c007-d259-454a-8b8d-5be914964afd")>': No scheme supplied. Perhaps you meant https://<selenium.webdriver.firefox.webdriver.WebDriver (session="4ff4c007-d259-454a-8b8d-5be914964afd")>?
```
**_fromdriver:_** 
```
AttributeError: 'WebDriver' object has no attribute 'find_element_by_tag_name'
```

**To Reproduce**
```
driver = webdriver.Firefox()
driver.get('https://www.amazon.com/errors/validateCaptcha')

captcha = AmazonCaptcha.fromlink(driver)
solution = captcha.solve()
```

**Desktop (please complete the following information):**
```
macOS Ventura
Firefox 112.0.2 (64-bit)
```

**Additional context**
```
Hopefully it's something simple.
```

**Comment by a-maliarov** [comment] 2023-05-14 13:00
Hi, `'WebDriver' object has no attribute 'find_element_by_tag_name' ` is caused by selenium not using `'find_element_by_tag_name'` anymore. I'm thinking on how to fix this without making selenium a dependency, but, please, wait with this one.

Regarding `fromlink`, you are using it incorrectly, since it accepts the link (while you were trying to pass a driver). For example:
```python
from amazoncaptcha import AmazonCaptcha

links = [
    'https://images-na.ssl-images-amazon.com/captcha/bfhuzdtn/Captcha_cebmxydbrt.jpg',
    'https://images-na.ssl-images-amazon.com/captcha/perumqgc/Captcha_gaommpndkq.jpg',
    'https://images-na.ssl-images-amazon.com/captcha/rhnrlggh/Captcha_tijaodpupx.jpg',
    'https://images-na.ssl-images-amazon.com/captcha/bysppkyq/Captcha_xroxbnvmrg.jpg'
]

for link in links:    
    captcha = AmazonCaptcha.fromlink(link)
    print(captcha.solve())
```

All you need to do now is extract the image link from your driver page source and pass it to `fromlink`. It is more stable than `fromdriver` anyways, while the fix for the latter will be ready later.
```python
from webdriver_manager.chrome import ChromeDriverManager
from amazoncaptcha import AmazonCaptcha
from selenium import webdriver

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get('https://www.amazon.com/errors/validateCaptcha')

# Extract captcha image link in any comfortable way, you could use BeautifulSoup, CssSelect or whatever.
captcha_link = driver.page_source.split('<img src="')[1].split('">')[0]
# Pass the link to `fromlink`.
captcha = AmazonCaptcha.fromlink(captcha_link)
print(captcha.solve())
```

**Comment by a-maliarov** [comment] 2023-05-14 13:39
`'WebDriver' object has no attribute 'find_element_by_tag_name'` should also be fixed now

**Closed by a-maliarov** 2023-05-14 13:39 UTC
Labels: bug
